title: Henrique Nunes
url: "https://henriqnuns.github.io/"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

# remote_theme: ankitsultana/researcher@gh-pages

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "resume.pdf" # put your files in the assets directory
 - name: "About"
   link: "/henriqnuns.github.io/"
