title: Henrique Nunes
url: "https://henriqnuns.com.br"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Sobre"
   link: "/"
 - name: "Lattes"
   link: "http://lattes.cnpq.br/3045987981563493"
 - name: "Contato"
   link: "contato"
